language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

install:
  - npm install -q

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  target-branch: $GITHUB_BRANCH
  github-token: $GITHUB_TOKEN
  verbose: true

branches:
  only:
    - master
